### ISSUE TITLE
Restore Tab has conflicts against Outliner Plug In and breaks

### ISSUE THREAD

**Issue by ianTevesAcc** [jrymk/restore-tab-key#9]
When using the plug in "Restore Tab Key" and "Obsidian Outliner" together, it results in errors whenever indenting a group of bullet points. 

An example of this is by trying to indent the following group of bulletpoints which do not indent.
![image](https://github.com/jrymk/restore-tab-key/assets/105651670/db967fc8-fcb2-40a6-8f19-e8ca1b6a6f66)
instead it result into a large amount of repeating errors of 34 identical errors.
![image](https://github.com/jrymk/restore-tab-key/assets/105651670/6357d9f6-6e72-4a09-ae9a-2bec907c7296)
The following is he error message.
RangeError: Maximum call stack size exceeded
    at t.getCursor (app.js:1:1250775)
    at MyEditor.getCursor (index.ts:65:19)
    at OperationPerformer.perform (OperationPerformer.ts:32:21)
    at ListsMovementCommands.indentList (ListsMovementCommands.ts:86:63)
    at Object.eval [as editorCallback] (createEditorCallback.ts:8:35)
    at e.mobileOnly.Mt.isMobile.e.checkCallback (app.js:1:1835420)
    at o_ (app.js:1:1834718)
    at e.executeCommand (app.js:1:1836282)
    at e.executeCommandById (app.js:1:1836189)
    at run (plugin:restore-tab-key:62:24)
    
If you try to indent the group of bullet points even after failing, Obsidian eventually crashes.
![image](https://github.com/jrymk/restore-tab-key/assets/105651670/cc9b293f-c5e5-4a4f-b325-66b37327e3f1)

**Comment by jrymk** [comment]
Apparently Obsidian Outliner plugin calls the Tab key action when its indent list action is called, causing a recursive call loop.
I haven't located where the call happened from Outliner, but the issue should be fixed for now in 1.12.0.
